### ISSUE TITLE
Example to go from filename/folder to AST

### ISSUE THREAD

**Issue by desugaring** [jemc/ponycc#7]
I'm looking into creating a very very simple visual studio code language server to provide:
- method code completion
- go to definition
- red underline to show compiler errors

I can get error messages from ponyc, but it does not provide me with an AST to work with.

This is where I've come across your project.

A simple pony playground gist that goes from filename/folder to AST would be fantastic. This is assuming the AST keeps the source location of each AST node around - without that, go to definition would be quite tricky to do :)

**Comment by jemc** [comment]
I'd still like to help with this - I've just been swamped with other stuff this past week.

Let me know if you're still interested in it.
